language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: rbx-19mode     # We have some failing specs we need to take care of
notifications:
  recipients:
    - wael.nasreddine@gmail.com
