# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

$: << File.expand_path('../../lib/contao.rb', __FILE__)

require 'active_support/core_ext/kernel/reporting'
require 'contao'
require 'fakefs/spec_helpers'
require 'pry'

Dir["#{File.expand_path('../support', __FILE__)}/**/*.rb"].each {|f| require f}

RSpec.configure do |c|
  c.treat_symbols_as_metadata_keys_with_true_values = true
  c.run_all_when_everything_filtered = true
  c.filter_run :focus

  c.include FakeFS::SpecHelpers, :fakefs

  c.before :each do
    Rails.env  = 'development'
    Rails.root = '/root/my_awesome_project'

    Rails.application.config.tap do |config|
      config.contao.path = 'contao'
    end

    silence_warnings do
      TechnoGate::Contao::UI = stub('UI').as_null_object
    end
  end
end
